In [82]:
import numpy as np#导入numpy库并配置一个别名np
#传统的python语法
def pysum():
    a=[0,1,2,3,4]
    b=[9,8,7,6,5]
    c=[]
    for i in range(len(a)):
        c.append(a[i]**2+b[i]**2)
    return c
print(pysum())




[81, 65, 53, 45, 41]


In [3]:
#运用numpy的思想
def npsum():
    a=np.array([0,1,2,3,4])
    b=np.array([9,8,7,6,5])
    c=a**2+b**2
    return c
print(pysum())

[81, 65, 53, 45, 41]


In [12]:
#np.array()函数创建数组对象
a=[4,56,567,4]
b=[23,54,6,78]
n=np.array([a,b])
print(n)

[[  4  56 567   4]
 [ 23  54   6  78]]


In [22]:
#np.arange()函数创建数组  只能创建一维数组
u=np.arange(9)
ui=np.array([np.arange(9),np.arange(9,18)])
print(ui)



[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]]


In [30]:
#np.ones()  np.zeros() np.full(shape,val) np.eye()
u2=np.ones((2,3,4))
print(u2)
print('------分割线------')
u3=np.zeros((3,3,3))
print(u3)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
------分割线------
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [35]:
u4=np.full((3,4),26)
print(u4)
print('------分割线------')
u5=np.eye(4)
print(u5)
print('------分割线------')
u6=np.concatenate([u4,u5])#将两个或者多个数组合并为一个新的数组
print(u6)

[[26 26 26 26]
 [26 26 26 26]
 [26 26 26 26]]
------分割线------
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
------分割线------
[[26. 26. 26. 26.]
 [26. 26. 26. 26.]
 [26. 26. 26. 26.]
 [ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [46]:
#ndarray数组的维度变换
u8=u6.reshape((2,14))
print(u8)
print('------分割线------')
print(u6)
print('------分割线------')
u9=u8.flatten()#对数组进行降维返回一维数组（不改变原数组）
print(u9)
print('------分割线------')
print(u8)

[[26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26.  1.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  1.  0.  0.  0.  0.  1.]]
------分割线------
[[26. 26. 26. 26.]
 [26. 26. 26. 26.]
 [26. 26. 26. 26.]
 [ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
------分割线------
[26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26.  1.  0.  0.  0.  0.  1.
  0.  0.  0.  0.  1.  0.  0.  0.  0.  1.]
------分割线------
[[26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26.  1.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  1.  0.  0.  0.  0.  1.]]


In [51]:
#数组的拷贝和转换 new_a=a1.astype()   new_2=a.tolist()
a1=np.array([np.arange(9),np.arange(51,60)])
print(a1)
a2=a1.tolist()
print(type(a2))
print(a2)


[[ 0  1  2  3  4  5  6  7  8]
 [51 52 53 54 55 56 57 58 59]]
<class 'list'>
[[0, 1, 2, 3, 4, 5, 6, 7, 8], [51, 52, 53, 54, 55, 56, 57, 58, 59]]


In [63]:
#numpy数组的属性 n.ndim n.shape n.size n.dtype n.itemsize
print(n.ndim)
print(n.shape)
print(n.size)
print(n.dtype)

2
(2, 4)
8
int32


In [56]:
#数组的操作 即 ；索引和切片
#一维数组的索引与切片
a3=np.array([9,8,7,6,5])
print(a3[2])#索引
print(a3[1:4:2])#切片
print((a3[1:4:2]).tolist())

7
[8 6]
[8, 6]


In [69]:
#多维数组的索引与切片
a4=np.arange(24).reshape((2,3,4))
print(a4)
print('------分割线------')
print(a4[0,1,2])#索引
print(a4[1,2,3])
print(a4[1,1,1])
print('------分割线------')
print(a4[0,1,:3])#切片
print(a4[:,1,1:3])


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
------分割线------
6
23
17
------分割线------
[4 5 6]
[[ 5  6]
 [17 18]]


In [65]:
print('王凯旋是天才')

王凯旋是天才


In [76]:
#数组的运算  一元函数
n=np.arange(24).reshape((2,3,4))
print(n)
print('------分割线------')
print(n*2)
print('------分割线------')
print(np.square(n))#计算数组各元素的平方值
print('------分割线------')
print(np.mean(n))#计算数组各元素的平均值
print('------分割线------')
print(np.abs(n))


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
------分割线------
[[[ 0  2  4  6]
  [ 8 10 12 14]
  [16 18 20 22]]

 [[24 26 28 30]
  [32 34 36 38]
  [40 42 44 46]]]
------分割线------
[[[  0   1   4   9]
  [ 16  25  36  49]
  [ 64  81 100 121]]

 [[144 169 196 225]
  [256 289 324 361]
  [400 441 484 529]]]
------分割线------
11.5
------分割线------
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [79]:
#数组的运算二元函数
ji=np.arange(12).reshape(2,2,3)
ji2=np.sqrt(ji)
print(ji)
print(ji2)
print('------分割线------')
print(ji<ji2)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[[0.         1.         1.41421356]
  [1.73205081 2.         2.23606798]]

 [[2.44948974 2.64575131 2.82842712]
  [3.         3.16227766 3.31662479]]]
------分割线------
[[[False False False]
  [False False False]]

 [[False False False]
  [False False False]]]


In [91]:
#csv文件的存储
a9=np.arange(24).reshape(4,6)
np.savetxt("C:\\Users\86666\Desktop\python文件处理\9.csv",a9,fmt='%d',delimiter=',')
print('写入成功')

写入成功


In [93]:
#csv文件的读取
wenjian=np.loadtxt('C:\\Users\86666\Desktop\python文件处理\9.csv',dtype=np.int32,delimiter=',')
print(wenjian)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [103]:
#多维数组的储存
hu=np.arange(36).reshape(2,3,6)
hu.tofile('C:\\Users\86666\Desktop\python文件处理\qw.dat',sep=',',format='%d')
print('写入成功')

写入成功


In [108]:
#多维数组的读取
shu=np.fromfile('C:\\Users\86666\Desktop\python文件处理\qw.dat',dtype=int,sep=',').reshape(hu.shape)
print(shu)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]]

 [[18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]]


In [116]:
#numpy数组便捷的读取方法
u=np.arange(12).reshape(2,6)
print(u)
#保存 np.save()
np.save('C:\\Users\86666\Desktop\python文件处理\wenjian.npy',u)
print('保存成功')

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
保存成功


In [117]:
#读取
ji3=np.load('C:\\Users\86666\Desktop\python文件处理\wenjian.npy')
print(ji3)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [118]:
h1=np.random.randint(1,10,(2,5))#np.random.randint(low,high,shape)返回shape形状的数组，取值在low到high范围内不包含high
print(h1)

[[9 2 6 6 2]
 [9 8 9 7 9]]


In [120]:
h2=np.random.rand(2,3,4)#返回shape形状的数组，随机数均匀分布，疯不范围为0~1不包含1
print(h2)

[[[0.80660863 0.07148294 0.58898961 0.80075252]
  [0.51304242 0.44267427 0.33170935 0.77407807]
  [0.97560829 0.57057768 0.98340317 0.6795504 ]]

 [[0.07133507 0.47110239 0.73087175 0.4484299 ]
  [0.74182851 0.26654931 0.9085308  0.70901756]
  [0.28400963 0.02020862 0.80002886 0.48409791]]]


In [123]:
h3=np.random.randn(1,10,2)#根据shape返回正态分布的数组
h3

array([[[-1.1917961 ,  0.81738878],
        [ 0.22580124,  0.70215689],
        [-0.10868319, -0.54130099],
        [-0.76359251,  0.34694467],
        [ 0.44666535, -1.20524731],
        [ 0.74106358,  1.28515353],
        [-0.42427781, -0.85128507],
        [ 0.39206988, -1.00653362],
        [-0.61646915,  1.81817458],
        [ 1.1717419 ,  0.75461763]]])

In [ ]:
h4=np.random.choice()

In [130]:
#numpy统计函数 
u=np.arange(36).reshape(2,3,6)
print(np.sum(u))#计算数组所有元素的和
print(np.min(u))
print(np.max(u))
print(np.ptp(u))


630
0
35
35


In [134]:
#numpy的梯度函数
ji=np.random.randint(0,20,(5))
print(ji)
print(np.gradient(ji))

[ 4  3 19  9 11]
[-1.   7.5  3.  -4.   2. ]
