In [7]:
print(type(date1))#查看数组的数据类型


<class 'numpy.ndarray'>


In [28]:
import numpy as np
date=[4,3,6,34,5]
date2=[[89,34],[90,8934,4],[54,65,23]]
date1=np.array(date)#array函数创建数组
print(date1)
date3=np.array([[89,34],[8934,4]])#创建数组的时候子元素的子元素数据个数必须相同
print(date3)

[ 4  3  6 34  5]
[[  89   34]
 [8934    4]]


In [25]:
c=[1,2,3,4]
d=[1,2,3,4]
d1=np.array(d)#用array函数创建数组
print(c*2)#列表的乘法
print(d1*2)#数组的乘法

[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]


In [24]:
 #创建多维数组
m=np.array([np.arange(2),np.arange(2)])
m

array([[0, 1],
       [0, 1]])

In [27]:
print(m.shape)#shape属性数组的形状
print(m.dtype)#数组的类型

(2, 2)
int32


In [47]:
ww=np.arange(1,9,0.5)#创建一维数组
print(ww)
w2=np.ones((3,2,6))#创建全1数组
print(w2)
w3=np.zeros((2,4,5))#创建全零数组
print(w3)
w4=np.eye(5)#创建正方形对角线全为1的数组
print(w4)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5]
[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]]
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [49]:
i=np.concatenate((ww,w2))
print(i)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 3 dimension(s)

In [1]:
history

history
